### ISSUE TITLE
Duplicate imports with different aliases end up with the same alias

### ISSUE THREAD

**Issue by sagikazarmark** [daixiang0/gci#1]
Given the following imports:

```go
import (
    "path/to/import/a"
    b "path/to/import/a"
)
```

After running the fixer on a file they will end up like this:

```go
import (
    b "path/to/import/a"
    b "path/to/import/a"
)
```

Which messes up the code quite a bit. IMHO this shouldn't be allowed by the compiler in the first place, but (sadly) it is.

*Note:* I use golangci-lint 1.30.0

**Comment by daixiang0** [comment]
Now `gci` foucs on import package group since i do not want to replace `goimports`. In this way, i recommend that you call `goimports` first.

**Comment by MatthewDolan** [comment]
Running `goimports` first does not resolve this issue.

In both examples below, the situation might be unexpected (probably recommended that the code does something different), but since the code is valid Go and valid go after having run `goimports`, I would expect this formatter to not make the code invalid.

This feels like a bug.

## Example 1

```
package example

import (
	a "github.com/example/nested"
	b "github.com/example/nested"
)
```

Running `goimports` is a noop.

```
> goimports -d .

```

This code is valid, compiles, and passes `goimports`.

Running `gci` rewrites the file to be invalid.

```
gci -d .      
diff -u example.go.orig example.go
--- example.go.orig	2020-09-01 08:44:57.000000000 -0700
+++ example.go	2020-09-01 08:44:57.000000000 -0700
@@ -2,7 +2,7 @@
 
 import (
 	a "github.com/example/nested"
-	b "github.com/example/nested"
+	a "github.com/example/nested"
 )
```

## Example 2

This also comes up when one import has an `_` and the second does not.

```
package example

import (
	_ "github.com/example/nested"

	"github.com/example/nested"
)
```

`goimports` does not change this file.

```
> goimports -d .

```

Running `gci` rewrites the file to be invalid.

```
> gci -d .
diff -u example.go.orig example.go
--- example.go.orig	2020-09-01 08:48:58.000000000 -0700
+++ example.go	2020-09-01 08:48:58.000000000 -0700
@@ -2,8 +2,7 @@
 
 import (
 	_ "github.com/example/nested"
-
-	"github.com/example/nested"
+	_ "github.com/example/nested"
 )
```
