### ISSUE TITLE
Local flag not working with non URL package names

### ISSUE THREAD

**Issue by andrazk** [daixiang0/gci#17]
In my project I'm using single name like `foo` instead of full URL package names (e.g. `github.com/user/foo`). In cases like this `local` flag is not used and packages are not grouped after 3rd party packages. 

### Example 

Here is a simplified example of the problem.

Go version: 1.15.1
GCI version: 0.2.4

go.mod
```
module foo

go 1.15
```

main.go
```go
package main

import (
	"fmt"

	"foo/bar"
)

func main() {
	fmt.Println("foo", bar.Bar())
}
```

### Actual output

```bash
> gci -d -local foo main.go
diff -u main.go.orig main.go
--- main.go.orig        2020-09-23 12:48:27.973264200 +0200
+++ main.go     2020-09-23 12:48:27.973822200 +0200
@@ -2,7 +2,6 @@
 
 import (
        "fmt"
-
        "foo/bar"
 )
```

### Expected output

The expected behavior should be for command to pass without errors.

**Comment by jamesvoong** [comment]
I am also seeing this on 0.2.4 and 1.14.1, also occurs through golangci-lint

**Comment by kwo** [comment]
I am having the same issue as I also use module names that are a single word and not a URL. The culprit is the following line in the function getPkgType https://github.com/daixiang0/gci/blob/master/pkg/gci/gci.go#L161 . Apparently, is a package name does not contain a dot, it is considered to be part of the standard library. The function could be changed to first check if the line in question starts with the local flag, and then to determine if the package name is part of the stdlib or not.
