### ISSUE TITLE
Cannot run GCI with -s localmodule flag

### ISSUE THREAD

**Issue by F0rzend** [daixiang0/gci#193]
### What version of GCI are you using?

<pre>
v0.13.0
</pre>

### Reproduce Steps

I run from root of my project with relative path to the file:
![image](https://github.com/daixiang0/gci/assets/50886859/50858e97-0458-4b9e-9093-146748d74a28)

### What did you expect to see?
Successfully formatted file

### What did you see instead?
Error: error reading local packages: [-: no Go files in <Project Root>]

**Comment by daixiang0** [comment]
@F0rzend could you share a case as simple as possible to reproduce it?

**Comment by CarlosRDomin** [comment]
Same here 😭  
I'll try to share a minimum reproducible example tomorrow if @F0rzend doesn't beat me to it :)

**Comment by petr-korobeinikov** [comment]
👋 

#192 should solve problem above.

**Comment by petr-korobeinikov** [comment]
Looking forward to see a minimal example...

**Comment by matthewhughes934** [comment]
Has this issue been raised with `golangci-lint`? I ask because it might be a blocker for releasing this feature upstream and I see `gci` has already been updated (but not included in any release) to include the change with https://github.com/golangci/golangci-lint/commit/9c492afc8396d16bb640661afecf8e2968f04c60. That is, it might be worth reverting that change if it's not certain a fix will be available in time for whenever `golangci-lint` plans on making their next release

**Comment by CarlosRDomin** [comment]
Apologies, it's been a busy week. I haven't had enough time to provide a minimum reproducible example but I can confirm that https://github.com/daixiang0/gci/pull/192 fixes the problems with my repo and everything works as expected!! Thank you so much @petr-korobeinikov for your great work, also the new tests look great :)
