### ISSUE TITLE
Rework module detection for golangci-lint integration

### ISSUE THREAD

**Issue by F0rzend** [daixiang0/gci#195]
### What version of GCI are you using?

<pre>
v0.13.1
</pre>

### Problem

Golangci-lint cannot use latest version of the gci.

Reason described in the [comment](https://github.com/golangci/golangci-lint/pull/4522#issuecomment-2002495737)

**Comment by daixiang0** [comment]
@CarlosRDomin not hard to do it, you can add modinfo in https://github.com/daixiang0/gci/blob/master/pkg/analyzer/analyzer.go#L44, then you can get mod file obj in the https://github.com/daixiang0/gci/blob/master/pkg/analyzer/analyzer.go#L50.

**Comment by CarlosRDomin** [comment]
Apologies for the delay, I've been fairly busy and just had a bit of time to take a look into the issue.

Based on [this comment](https://github.com/golangci/golangci-lint/pull/4522#issuecomment-2002495737), the issue is with [`findLocalModule` directly reading `go.mod`](https://github.com/daixiang0/gci/blob/master/pkg/section/local_module.go#L50), not in the analyzer itself. I unfortunately would need @ldez's expertise here (or @daixiang0's), I've never use Golang's analysis package but based on the docs I can only find a way to run the static analysis through [`singlechecker.Main`](https://github.com/golang/tools/blob/master/go/analysis/singlechecker/singlechecker.go#L39), which doesn't work since that executes the analyzer as the main command and exits, but instead the current code expects the `findLocalModule` to retrieve the package it is being called from and continue with the rest of the gci business logic.

I don't have enough knowledge to make gci runnable inside golangci-lint without any further help. @ldez, out of curiosity, have you already tried running the latest gci through golangci-lint and you saw errors or what made you think that this wouldn't work? Do you have a failing test I could run with a debugger and try to fix? I'd love to help but really don't know how at this point :(

**Comment by ldez** [comment]
> have you already tried running the latest gci through golangci-lint and you saw errors or what made you think that the current implementation wouldn't work? 

I don't need to run it to know that just reading a `go.mod` inside the current dir will never work as expected when you run golangci-lint inside a package.

---

The problem here is still the same: the design.

The elements inside [this comment](https://github.com/daixiang0/gci/issues/195#issuecomment-2011092207) are not helpful because the information about that module requires the `pass` but the `LocalModule` needs to access this information here:

https://github.com/daixiang0/gci/blob/4725b0c101801e7449530eee2ddb0c72592e3405/pkg/section/local_module.go#L38

https://github.com/daixiang0/gci/blob/4725b0c101801e7449530eee2ddb0c72592e3405/pkg/config/config.go#L96-L106

https://github.com/daixiang0/gci/blob/4725b0c101801e7449530eee2ddb0c72592e3405/pkg/config/config.go#L43-L54

And so, to every call to `YamlConfig.Parse()` but those calls happen before the setup and the run of the analyzer: so it's impossible to access the `pass`.

**Comment by ldez** [comment]
After digging more into the code: it's impossible to get something to work as expected without rewriting a large part of the gci code (and not extending it).

@CarlosRDomin, without deeply changing the gci design it's useless to try to fix that inside gci.
So, I will be forced to borrow some pieces of gci code and rewrite them inside golangci-lint, it's not a good sign.

At some point, if the design doesn't evolve in the right direction, either we will have all the code of gci, "customized" and inside golangci-lint, or we will have to fork it, or just use another linter.

When 500 LOC becomes more than 3000 LOC to provide the same thing as before, and the usage as a lib is unexpectedly complex, requires a lot of plumbing, and to borrow the code, I think it's just honest to say that there is a major design problem.

**Comment by daixiang0** [comment]
Now GCI use Analyzer layer to integrate with Golangci-lint like some linters do, I have added this in https://github.com/daixiang0/gci/issues/86 TODO.

For this issue, please see [this](https://github.com/daixiang0/gci/pull/196).

**Comment by ldez** [comment]
The "fix" (a copy of my hack) is in the continuity of the current design problems of gci.
The core of the design problem is not fixed and should be fixed.

**Comment by ccoVeille** [comment]
> The "fix" (a copy of my hack) is in the continuity of the current design problems of gci. The core of the design problem is not fixed and should be fixed.

@ldez does an amazing job on`golangci`, and I assume he is a nice guy. But this comment sounded a bit rude to me :sweat_smile: 

I'm sure a smiley would have helped.

Respectfully, a fan of `gci` and `golangci-lint`

**Comment by ldez** [comment]
> But this comment sounded a bit rude to me.

Because it is, I'm not happy with the situation, so I will not add any simley.

You are nice, but I don't need help handling this situation the way I want.
